"""initial schema

Revision ID: f58178dfdc52
Revises: 
Create Date: 2026-08-20 20:17:51.283967
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f58178dfdc52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_user_id', sa.BigInteger(), nullable=False),
    sa.Column('github_login', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_github_user_id'), 'users', ['github_user_id'], unique=True)
    op.create_table('github_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('connected_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], name=op.f('fk_github_installations_connected_by_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_installations'))
    )
    op.create_index(op.f('ix_github_installations_installation_id'), 'github_installations', ['installation_id'], unique=True)
    op.create_table('github_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(length=2048), nullable=True),
    sa.Column('token_type', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_github_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_tokens')),
    sa.UniqueConstraint('user_id', name=op.f('uq_github_tokens_user_id'))
    )
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('owner_login', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('html_url', sa.String(length=1024), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['github_installations.id'], name=op.f('fk_repositories_installation_id_github_installations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('github_repo_id', name='uq_repositories_github_repo_id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=False)
    op.create_index(op.f('ix_repositories_github_repo_id'), 'repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_repositories_installation_id'), 'repositories', ['installation_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('runs_analyzed_count', sa.Integer(), nullable=False),
    sa.Column('analyzer_errors', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_analyses_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index(op.f('ix_analyses_repository_id'), 'analyses', ['repository_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_workflow_id', sa.BigInteger(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_workflows_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows')),
    sa.UniqueConstraint('repository_id', 'github_workflow_id', name='uq_workflows_repository_github_id')
    )
    op.create_index(op.f('ix_workflows_github_workflow_id'), 'workflows', ['github_workflow_id'], unique=False)
    op.create_index(op.f('ix_workflows_repository_id'), 'workflows', ['repository_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('analyzer_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('estimated_savings_low_seconds', sa.Float(), nullable=True),
    sa.Column('estimated_savings_high_seconds', sa.Float(), nullable=True),
    sa.Column('estimated_savings_basis', sa.String(length=512), nullable=True),
    sa.Column('estimated_savings_unknown', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_findings_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_analysis_id'), 'findings', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_findings_analyzer_type'), 'findings', ['analyzer_type'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_run_id', sa.BigInteger(), nullable=False),
    sa.Column('run_attempt', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conclusion', sa.String(length=32), nullable=True),
    sa.Column('run_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_workflow_runs_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_runs_workflow_id_workflows'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs')),
    sa.UniqueConstraint('github_run_id', 'run_attempt', name='uq_workflow_runs_github_run_attempt')
    )
    op.create_index(op.f('ix_workflow_runs_github_run_id'), 'workflow_runs', ['github_run_id'], unique=False)
    op.create_index('ix_workflow_runs_repository_created', 'workflow_runs', ['repository_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_repository_id'), 'workflow_runs', ['repository_id'], unique=False)
    op.create_index('ix_workflow_runs_workflow_created', 'workflow_runs', ['workflow_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_job_id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conclusion', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runs_on', sa.String(length=255), nullable=True),
    sa.Column('run_attempt', sa.Integer(), nullable=False),
    sa.Column('needs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_jobs_workflow_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('github_job_id', name='uq_jobs_github_job_id')
    )
    op.create_index(op.f('ix_jobs_github_job_id'), 'jobs', ['github_job_id'], unique=True)
    op.create_index(op.f('ix_jobs_workflow_run_id'), 'jobs', ['workflow_run_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conclusion', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_steps_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_steps')),
    sa.UniqueConstraint('job_id', 'number', name='uq_steps_job_number')
    )
    op.create_index(op.f('ix_steps_job_id'), 'steps', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steps_job_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_jobs_workflow_run_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_github_job_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_workflow_created', table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_repository_id'), table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_repository_created', table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_github_run_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_analyzer_type'), table_name='findings')
    op.drop_index(op.f('ix_findings_analysis_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_workflows_repository_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_github_workflow_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_analyses_repository_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_repositories_installation_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_repo_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('github_tokens')
    op.drop_index(op.f('ix_github_installations_installation_id'), table_name='github_installations')
    op.drop_table('github_installations')
    op.drop_index(op.f('ix_users_github_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
